blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('details/<int:post_id>/', views.blog_details, name='blog_details'),
    path('details/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('category/<slug:category_slug>/', views.blog_by_category, name='blog_by_category'),
    path('tag/<slug:tag_slug>/', views.blog_by_tag, name='blog_by_tag'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('update/', views.cart_update, name='cart_update'),
    path('remove-ajax/', views.cart_remove_ajax, name='cart_remove_ajax'),
]

orders/urls.py
from django.urls import path
from . import views
from .views import save_guest_info

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('created/', views.order_created, name='order_created'),
    path('save-guest-info/', save_guest_info, name='save_guest_info'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import logout_view, update_account, update_address, quick_view

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('login-register/', views.login_register, name='login_register'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('my-account/', views.my_account, name='my_account'),
    path('update-account/', update_account, name='update_account'),
    path('update-address/', update_address, name='update_address'),
    path('shop-page/', views.shop_page, name='shop_page'),
    path('shop-page/<str:category_type>/<slug:category_slug>/', views.shop_page, name='shop_page_by_category'),
    path('shop-list/', views.shop_list, name='shop_list'),
    path('shop-list/<str:category_type>/<slug:category_slug>/', views.shop_list, name='shop_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_details, name='product_detail'),
    path('food-category/<slug:category_slug>/', views.product_list_by_food_category,
         name='product_list_by_food_category'),
    path('pet-category/<slug:category_slug>/', views.product_list_by_pet_category, name='product_list_by_pet_category'),
    path('brand/<slug:brand_slug>/', views.product_list_by_brand, name='product_list_by_brand'),
    path('search/', views.search_products, name='search_products'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('quick-view/<int:product_id>/', quick_view, name='quick_view'),
    path('subscribe/', views.subscribe_newsletter, name='subscribe_newsletter'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from shop.models import Product, NewsletterSubscription
from .cart import Cart
from django.http import JsonResponse
from django.contrib import messages


def cart_detail(request):
    cart = Cart(request)
    email = request.user.email if request.user.is_authenticated else request.session.get('guest_email')

    discount, coupon_code = cart.get_discount(email)
    grand_total = cart.get_total_price_after_discount(email)

    if request.method == 'POST':
        coupon_input = request.POST.get('coupon_code')
        if coupon_input:
            try:
                subscription = NewsletterSubscription.objects.get(coupon_code=coupon_input, coupon_used=False)
                if subscription.email == email or not request.user.is_authenticated:
                    discount, coupon_code = cart.apply_coupon(subscription.email)
                    grand_total = cart.get_total_price_after_discount(subscription.email)
                    messages.success(request, "Coupon applied successfully!")
                else:
                    messages.error(request, "Invalid coupon code.")
            except NewsletterSubscription.DoesNotExist:
                messages.error(request, "Invalid or already used coupon code.")

    return render(request, 'cart/cart.html', {
        'cart': cart,
        'discount': discount,
        'coupon_code': coupon_code,
        'grand_total': grand_total
    })


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', request.GET.get('quantity', 1)))
    cart.add(product=product, quantity=quantity, update_quantity=True)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


def cart_update(request):
    cart = Cart(request)
    if request.method == 'POST':
        for key, value in request.POST.items():
            if key.startswith('quantity_'):
                product_id = key.split('_')[1]
                product = get_object_or_404(Product, id=product_id)
                quantity = int(value)
                cart.add(product=product, quantity=quantity, update_quantity=True)
    return redirect('cart:cart_detail')


def cart_remove_ajax(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return JsonResponse({
            'success': True,
            'total_price': cart.get_total_price(),
            'cart_count': len(cart)
        })
    return JsonResponse({'success': False}, status=400)

templates/cart/cart.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="breadcrumb-area pt-95 pb-95 bg-img" style="background-image:url({% static 'shop/img/banners/banner-2.jpg' %});">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <h2>Cart</h2>
            <ul>
                <li><a href="{% url 'shop:index' %}">home</a></li>
                <li class="active">Cart</li>
            </ul>
        </div>
    </div>
</div>
<div class="cart-main-area pt-95 pb-100">
    <div class="container">
        <h3 class="page-title">Your cart items</h3>
        {% if cart %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <form action="{% url 'cart:cart_update' %}" method="post">
                    {% csrf_token %}
                    <div class="table-content table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Unit Price</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                <tr>
                                    <td class="product-thumbnail">
                                        <a href="{{ item.product.get_absolute_url }}"><img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" style="width: 150px; height: auto;"></a>
                                    </td>
                                    <td class="product-name"><a href="{{ item.product.get_absolute_url }}">{{ item.product.name|truncatewords:3 }}</a></td>
                                    <td class="product-price-cart"><span class="amount">${{ item.price }}</span></td>
                                    <td class="product-quantity">
                                        <div class="cart-plus-minus">
                                            <input class="cart-plus-minus-box" type="number" name="quantity_{{ item.product.id }}" value="{{ item.quantity }}" min="1">
                                        </div>
                                    </td>
                                    <td class="product-subtotal">${{ item.total_price }}</td>
                                    <td class="product-remove">
                                        <a href="{% url 'cart:cart_remove' item.product.id %}"><i class="ti-trash"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="cart-shiping-update-wrapper">
                                <div class="cart-shiping-update">
                                    <a href="{% url 'shop:shop_page' %}">Continue Shopping</a>
                                    <button type="submit">Update Shopping Cart</button>
                                </div>
                                <div class="cart-clear">
                                    <a href="{% url 'cart:cart_clear' %}">Clear Shopping Cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="row">
                    {% if request.user.is_authenticated %}
                    <div class="col-lg-4 col-md-6">
                        <div class="discount-code-wrapper">
                            <h4 class="cart-bottom-title">DISCOUNT CODES</h4>
                            <div class="discount-code">
                                <p>Enter your coupon code if you have one.</p>
                                <form method="post" action="{% url 'cart:cart_detail' %}">
                                    {% csrf_token %}
                                    <input type="text" name="coupon_code" value="{% if coupon_code %}{{ coupon_code }}{% endif %}" required="">
                                    <button class="cart-btn-2" type="submit" {% if discount %} disabled {% endif %}>Apply Coupon</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    <div class="col-lg-4 col-md-12 offset-lg-4">
                        <div class="grand-totall">
                            <span>Subtotal: ${{ cart.get_total_price|floatformat:2 }}</span>
                            {% if discount %}
                                <span>Coupon Code Applied: {{ coupon_code }}</span>
                                <span>Discount: -${{ discount|floatformat:2 }}</span>
                            {% endif %}
                            <h5>Grand Total: ${{ grand_total|floatformat:2 }}</h5>
                            <a href="{% url 'orders:order_create' %}">Proceed To Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="cart-empty-title" style="display: {% if cart %}none{% else %}block{% endif %};">
            <h2>Your cart is currently empty.</h2>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}