blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('details/<int:post_id>/', views.blog_details, name='blog_details'),
    path('details/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('category/<slug:category_slug>/', views.blog_by_category, name='blog_by_category'),
    path('tag/<slug:tag_slug>/', views.blog_by_tag, name='blog_by_tag'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('update/', views.cart_update, name='cart_update'),
    path('remove-ajax/', views.cart_remove_ajax, name='cart_remove_ajax'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import logout_view, update_account, update_address, quick_view

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('login-register/', views.login_register, name='login_register'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('my-account/', views.my_account, name='my_account'),
    path('update-account/', update_account, name='update_account'),
    path('update-address/', update_address, name='update_address'),
    path('shop-page/', views.shop_page, name='shop_page'),
    path('shop-page/<str:category_type>/<slug:category_slug>/', views.shop_page, name='shop_page_by_category'),
    path('shop-list/', views.shop_list, name='shop_list'),
    path('shop-list/<str:category_type>/<slug:category_slug>/', views.shop_list, name='shop_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_details, name='product_detail'),
    path('food-category/<slug:category_slug>/', views.product_list_by_food_category,
         name='product_list_by_food_category'),
    path('pet-category/<slug:category_slug>/', views.product_list_by_pet_category, name='product_list_by_pet_category'),
    path('brand/<slug:brand_slug>/', views.product_list_by_brand, name='product_list_by_brand'),
    path('search/', views.search_products, name='search_products'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('quick-view/<int:product_id>/', quick_view, name='quick_view'),
    path('subscribe/', views.subscribe_newsletter, name='subscribe_newsletter'),
]

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_detail, name='wishlist_detail'),
    path('add/<int:product_id>/', views.wishlist_add, name='wishlist_add'),
    path('remove/<int:item_id>/', views.wishlist_remove, name='wishlist_remove'),
]

wishlist/models.py
from django.conf import settings
from django.db import models
from shop.models import Product


class WishlistItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} in {self.user.username}'s wishlist"

    def subtotal(self):
        return self.quantity * self.product.new_price

wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import WishlistItem
from shop.models import Product


@login_required
def wishlist_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', 1))
    wishlist_item, created = WishlistItem.objects.get_or_create(user=request.user, product=product)
    if not created:
        wishlist_item.quantity += quantity
    wishlist_item.save()
    return redirect('wishlist:wishlist_detail')


@login_required
def wishlist_remove(request, item_id):
    wishlist_item = get_object_or_404(WishlistItem, id=item_id, user=request.user)
    wishlist_item.delete()
    return redirect('wishlist:wishlist_detail')


@login_required
def wishlist_detail(request):
    wishlist_items = WishlistItem.objects.filter(user=request.user)
    return render(request, 'wishlist/wishlist.html', {'wishlist_items': wishlist_items})

templates/wishlist/wishlist.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="breadcrumb-area pt-95 pb-95 bg-img" style="background-image:url('{% static 'shop/img/banners/banner-2.jpg' %}');">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <h2>Wishlist</h2>
            <ul>
                <li><a href="{% url 'shop:index' %}">home</a></li>
                <li class="active">Wishlist</li>
            </ul>
        </div>
    </div>
</div>
<div class="cart-main-area pt-95 pb-100">
    <div class="container">
        <h3 class="page-title">Your wishlist items</h3>
        {% if wishlist_items %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <form action="#">
                    <div class="table-content table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Unit Price</th>
                                    <th>Qty</th>
                                    <th>Add To Cart</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in wishlist_items %}
                                <tr>
                                    <td class="product-thumbnail">
                                        <a href="{{ item.product.get_absolute_url }}"><img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" style="width: 150px; height: auto;"></a>
                                    </td>
                                    <td class="product-name"><a href="{{ item.product.get_absolute_url }}">{{ item.product.name|truncatewords:3 }}</a></td>
                                    <td class="product-price-cart"><span class="amount">${{ item.product.new_price }}</span></td>
                                    <td class="product-quantity">
                                        <div class="cart-plus-minus">
                                            <input class="cart-plus-minus-box" type="number" name="qtybutton" value="{{ item.quantity }}">
                                        </div>
                                    </td>
                                    <td class="product-wishlist-cart">
                                        <a href="{% url 'cart:cart_add' item.product.id %}">add to cart</a>
                                    </td>
                                    <td class="product-remove">
                                        <a href="{% url 'wishlist:wishlist_remove' item.id %}"><i class="ti-trash"></i></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
        {% else %}
        <div class="wishlist-empty-title">
            <h2>Your wishlist is currently empty.</h2>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}