blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('details/<int:post_id>/', views.blog_details, name='blog_details'),
    path('details/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('category/<slug:category_slug>/', views.blog_by_category, name='blog_by_category'),
    path('tag/<slug:tag_slug>/', views.blog_by_tag, name='blog_by_tag'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import logout_view, update_account, update_address, quick_view

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('login-register/', views.login_register, name='login_register'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('my-account/', views.my_account, name='my_account'),
    path('update-account/', update_account, name='update_account'),
    path('update-address/', update_address, name='update_address'),
    path('shop-page/', views.shop_page, name='shop_page'),
    path('shop-page/<str:category_type>/<slug:category_slug>/', views.shop_page, name='shop_page_by_category'),
    path('shop-list/', views.shop_list, name='shop_list'),
    path('shop-list/<str:category_type>/<slug:category_slug>/', views.shop_list, name='shop_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_details, name='product_detail'),
    path('food-category/<slug:category_slug>/', views.product_list_by_food_category,
         name='product_list_by_food_category'),
    path('pet-category/<slug:category_slug>/', views.product_list_by_pet_category, name='product_list_by_pet_category'),
    path('brand/<slug:brand_slug>/', views.product_list_by_brand, name='product_list_by_brand'),
    path('search/', views.search_products, name='search_products'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('quick-view/<int:product_id>/', quick_view, name='quick_view'),
    path('subscribe/', views.subscribe_newsletter, name='subscribe_newsletter'),
]

blog/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=100)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200)
    cover_image = models.ImageField(upload_to='blog/')
    content = HTMLField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    published_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    tags = models.ManyToManyField(Tag, related_name='posts')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author_name = models.CharField(max_length=100)
    author_email = models.EmailField()
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    avatar_url = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"Comment by {self.author_name} on {self.post.title}"

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author_name', 'author_email', 'content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Message'}),
            'author_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'author_email': forms.EmailInput(attrs={'placeholder': 'Email'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields['author_name'].initial = user.first_name
            self.fields['author_email'].initial = user.email
            self.fields['author_name'].widget.attrs['readonly'] = True
            self.fields['author_email'].widget.attrs['readonly'] = True
            self.fields['author_name'].required = False
            self.fields['author_email'].required = False
        else:
            self.fields['author_name'].required = True
            self.fields['author_email'].required = True

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.core.paginator import Paginator
from .models import Post, Category, Tag, Comment
from .forms import CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def blog(request):
    query = request.GET.get('q')
    category_slug = request.GET.get('category')
    tag_slug = request.GET.get('tag')

    posts = Post.objects.all().order_by('-published_date')

    if query:
        posts = posts.filter(title__icontains=query) | posts.filter(content__icontains=query)

    if category_slug:
        posts = posts.filter(category__slug=category_slug)

    if tag_slug:
        posts = posts.filter(tags__slug=tag_slug)

    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    categories = Category.objects.all()
    tags = Tag.objects.all()
    recent_posts = Post.objects.order_by('-published_date')[:3]

    context = {
        'posts': page_obj,
        'page_obj': page_obj,
        'categories': categories,
        'tags': tags,
        'recent_posts': recent_posts,
    }
    return render(request, 'blog/blog-leftsidebar.html', context)


def blog_details(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    recent_posts = Post.objects.order_by('-published_date')[:3]

    if request.method == 'POST':
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.author_name = request.user.first_name
                comment.author_email = request.user.email
                comment.save()
                messages.success(request, 'Your comment has been posted!')
                return redirect('blog:blog_details', post_id=post.id)
        else:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.save()
                messages.success(request, 'Your comment has been posted!')
                return redirect('blog:blog_details', post_id=post.id)
    else:
        form = CommentForm()

    context = {
        'post': post,
        'categories': categories,
        'tags': tags,
        'recent_posts': recent_posts,
        'form': form,
    }
    return render(request, 'blog/blog-details.html', context)


def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        if request.user.is_authenticated:
            author_name = request.user.first_name
            author_last_name = request.user.last_name
            author_email = request.user.email
            avatar_url = request.user.profile.avatar.url if request.user.profile.avatar else None
        else:
            author_name = request.POST.get('author_name')
            author_last_name = request.POST.get('author_last_name')
            author_email = request.POST.get('author_email')
            avatar_url = None

        content = request.POST.get('content')

        if not content:
            messages.error(request, "Comment content cannot be empty.")
            return redirect('blog:blog_details', post_id=post.id)

        if not author_name or not author_last_name or not author_email:
            messages.error(request, "Please provide your full name and email.")
            return redirect('blog:blog_details', post_id=post.id)

        full_author_name = f"{author_name} {author_last_name}"

        Comment.objects.create(
            post=post,
            author_name=full_author_name,
            author_email=author_email,
            content=content,
            avatar_url=avatar_url
        )

        messages.success(request, "Your comment has been posted.")
        return redirect('blog:blog_details', post_id=post.id)

    return redirect('blog:blog_details', post_id=post.id)


def blog_by_category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    posts = Post.objects.filter(category=category)
    return render(request, 'blog/blog.html', {'posts': posts, 'selected_category': category})


def blog_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = Post.objects.filter(tags=tag)
    return render(request, 'blog/blog.html', {'posts': posts, 'selected_tag': tag})

templates/blog/blog-details.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="breadcrumb-area pt-95 pb-95 bg-img" style="background-image:url('{% static 'shop/img/banners/banner-2.jpg' %}');">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <h2>Post Details</h2>
            <ul>
                <li><a href="{% url 'shop:index' %}">Home</a></li>
                <li class="active">Post Details</li>
            </ul>
        </div>
    </div>
</div>
<div class="shop-area pt-100 pb-100 blog-details-page">
    <div class="container">
        <div class="row flex-row-reverse">
            <div class="col-lg-9 col-md-8">
                <div class="blog-details-wrapper res-mrg-top">
                    <div class="single-blog-wrapper">
                        <div class="blog-img mb-30">
                            <img src="{{ post.cover_image.url }}" alt="{{ post.title }}">
                        </div>
                        <div class="blog-details-content">
                            <h2>{{ post.title }}</h2>
                            <div class="blog-meta">
                                <ul>
                                    <li>{{ post.published_date|date:"F d, Y" }}</li>
                                    <li>
                                        <a href="#"> {{ post.comments.count }} Comments</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="post-content">
                            {{ post.content|safe }}
                        </div>
                        <div class="blog-dec-tags-social mt-50">
                            <div class="blog-dec-tags">
                                <ul>
                                    {% for tag in post.tags.all %}
                                    <li><a href="{% url 'blog:blog' %}?tag={{ tag.slug }}">{{ tag.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="blog-dec-social">
                                <span>Share:</span>
                                <ul>
                                    <li><a href="#"><i class="icon-social-twitter"></i></a></li>
                                    <li><a href="#"><i class="icon-social-instagram"></i></a></li>
                                    <li><a href="#"><i class="icon-social-dribbble"></i></a></li>
                                    <li><a href="#"><i class="icon-social-linkedin"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="blog-comment-wrapper mt-55">
                        <h4 class="blog-dec-title">Comments: {{ post.comments.count }}</h4>
                        {% for comment in post.comments.all %}
                        <div class="single-comment-wrapper mt-35">
                            <div class="blog-comment-img">
                                {% if comment.avatar_url %}
                                <img src="{{ comment.avatar_url }}" alt="User Avatar" class="rounded-avatar">
                                {% else %}
                                <img src="{% static 'shop/img/logo.jpg' %}" alt="Default Avatar" class="rounded-avatar">
                                {% endif %}
                            </div>
                            <div class="blog-comment-content">
                                <h4>{{ comment.author_name }}</h4>
                                <span>{{ comment.published_date|date:"F d, Y" }}</span>
                                <p>{{ comment.content|linebreaksbr|truncatechars:500 }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="blog-reply-wrapper mt-50">
                        <h4 class="blog-dec-title">Post a Comment</h4>
                        <form action="{% url 'blog:add_comment' post.id %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                {% if request.user.is_authenticated %}
                                <div class="col-md-12">
                                    <div class="leave-form">
                                        <textarea name="content" placeholder="Message" maxlength="500" required></textarea>
                                    </div>
                                </div>
                                {% else %}
                                <div class="col-md-6">
                                    <div class="leave-form">
                                        <input type="text" name="author_name" placeholder="First Name" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="leave-form">
                                        <input type="text" name="author_last_name" placeholder="Last Name" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="leave-form">
                                        <input type="email" name="author_email" placeholder="Email Address" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="leave-form">
                                        <textarea name="content" placeholder="Message" maxlength="500" required></textarea>
                                    </div>
                                </div>
                                {% endif %}
                                <div class="col-md-12">
                                    <div class="text-leave">
                                        <input type="submit" value="SEND MESSAGE">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="shop-sidebar blog-mrg">
                    <div class="shop-widget">
                        <h4 class="shop-sidebar-title">Search</h4>
                        <div class="shop-search mt-25 mb-50">
                            <form class="shop-search-form" method="GET" action="{% url 'blog:blog' %}">
                                <input type="text" name="q" placeholder="Find a post">
                                <button type="submit"><i class="icon-magnifier"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="shop-widget mt-50">
                        <h4 class="shop-sidebar-title">Category</h4>
                        <div class="shop-list-style mt-20">
                            <ul>
                                {% for category in categories %}
                                <li><a href="{% url 'blog:blog' %}?category={{ category.slug }}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="shop-widget mt-50">
                        <h4 class="shop-sidebar-title">Tags</h4>
                        <div class="shop-list-style mt-20">
                            <ul>
                                {% for tag in tags %}
                                <li><a href="{% url 'blog:blog' %}?tag={{ tag.slug }}">{{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="shop-widget mt-50">
                        <h4 class="shop-sidebar-title">Recent Post</h4>
                        <div class="recent-post-wrapper mt-25">
                            {% for recent_post in recent_posts %}
                            <div class="single-recent-post mb-20">
                                <div class="recent-post-img">
                                    <a href="{% url 'blog:blog_details' recent_post.id %}"><img src="{{ recent_post.cover_image.url }}" alt="{{ recent_post.title }}"></a>
                                </div>
                                <div class="recent-post-content">
                                    <h4><a href="{% url 'blog:blog_details' recent_post.id %}">{{ recent_post.title }}</a></h4>
                                    <span>{{ recent_post.published_date|date:"F d, Y" }} </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/blog-leftsidebar.html
{% extends "shop/base.html" %}
{% load static %}
{% load pagination_tags %}
{% block content %}
<div class="breadcrumb-area pt-95 pb-95 bg-img" style="background-image:url('{% static 'shop/img/banners/banner-2.jpg' %}');">
    <div class="container">
        <div class="breadcrumb-content text-center">
            <h2>Blog</h2>
            <ul>
                <li><a href="{% url 'shop:index' %}">Home</a></li>
                <li class="active">Blog</li>
            </ul>
        </div>
    </div>
</div>
<div class="shop-area pt-100 pb-100">
    <div class="container">
        <div class="row flex-row-reverse">
            <div class="col-lg-9 col-md-8">
                <div class="row">
                    {% for post in posts %}
                    <div class="col-lg-6 col-md-12">
                        <div class="blog-wrapper mb-30 gray-bg">
                            <div class="blog-img hover-effect">
                                <a href="{% url 'blog:blog_details' post.id %}"><img alt="{{ post.title }}" src="{{ post.cover_image.url }}"></a>
                            </div>
                            <div class="blog-content">
                                <div class="blog-meta">
                                    <ul>
                                        <li>By: <span>{{ post.author.username }}</span></li>
                                        <li>{{ post.published_date|date:"F d, Y" }}</li>
                                    </ul>
                                </div>
                                <h4><a href="{% url 'blog:blog_details' post.id %}">{{ post.title }}</a></h4>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="pagination-style text-center mt-10">
                    <ul>
                        {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}">
                                <i class="icon-arrow-left"></i>
                            </a>
                        </li>
                        {% endif %}

                        {% get_pagination_range page_obj as pagination_range %}
                        {% for page_num in pagination_range %}
                            {% if page_num == '...' %}
                                <li><span>...</span></li>
                            {% else %}
                                <li {% if page_num == page_obj.number %}class="active"{% endif %}>
                                    <a href="?page={{ page_num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}">
                                        {{ page_num }}
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}">
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="shop-sidebar blog-mrg">
                    <div class="shop-widget">
                        <h4 class="shop-sidebar-title">Search</h4>
                        <div class="shop-search mt-25 mb-50">
                            <form class="shop-search-form" method="GET" action="{% url 'blog:blog' %}">
                                <input type="text" name="q" placeholder="Find a post">
                                <button type="submit"><i class="icon-magnifier"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="shop-widget mt-50">
                        <h4 class="shop-sidebar-title">Category</h4>
                        <div class="shop-list-style mt-20">
                            <ul>
                                {% for category in categories %}
                                <li><a href="{% url 'blog:blog' %}?category={{ category.slug }}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="shop-widget mt-50">
                        <h4 class="shop-sidebar-title">Tags</h4>
                        <div class="shop-list-style mt-20">
                            <ul>
                                {% for tag in tags %}
                                <li><a href="{% url 'blog:blog' %}?tag={{ tag.slug }}">{{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="shop-widget mt-50">
                        <h4 class="shop-sidebar-title">Recent Post</h4>
                        <div class="recent-post-wrapper mt-25">
                            {% for post in recent_posts %}
                            <div class="single-recent-post mb-20">
                                <div class="recent-post-img">
                                    <a href="{% url 'blog:blog_details' post.id %}"><img src="{{ post.cover_image.url }}" alt="{{ post.title }}"></a>
                                </div>
                                <div class="recent-post-content">
                                    <h4><a href="{% url 'blog:blog_details' post.id %}">{{ post.title }}</a></h4>
                                    <span>{{ post.published_date|date:"F d, Y" }}</span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/blog.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="breadcrumb-area pt-95 pb-95 bg-img" style="background-image:url('{% static 'shop/img/banners/banner-2.jpg' %}');">
<div class="container">
<div class="breadcrumb-content text-center">
    <h2>Blog</h2>
    <ul>
        <li><a href="index.html">home</a></li>
        <li class="active">Blog</li>
    </ul>
</div>
</div>
</div>
<div class="blog-area pt-100 pb-100 clearfix">
<div class="container">
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="blog-wrapper mb-30 gray-bg">
            <div class="blog-img hover-effect">
                <a href="blog-details.html"><img alt="" src="assets/img/blog/blog-4.jpg"></a>
            </div>
            <div class="blog-content">
                <div class="blog-meta">
                    <ul>
                        <li>By: <span>Admin</span></li>
                        <li>Sep 14, 2018</li>
                    </ul>
                </div>
                <h4><a href="blog-details.html">Lorem ipsum dolor amet cons adipisicing elit</a></h4>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="blog-wrapper mb-30 gray-bg">
            <div class="blog-img hover-effect">
                <a href="blog-details.html"><img alt="" src="assets/img/blog/blog-5.jpg"></a>
            </div>
            <div class="blog-content">
                <div class="blog-meta">
                    <ul>
                        <li>By: <span>Admin</span></li>
                        <li>Sep 14, 2018</li>
                    </ul>
                </div>
                <h4><a href="blog-details.html">Lorem ipsum dolor amet cons adipisicing elit</a></h4>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="blog-wrapper mb-30 gray-bg">
            <div class="blog-img hover-effect">
                <a href="blog-details.html"><img alt="" src="assets/img/blog/blog-6.jpg"></a>
            </div>
            <div class="blog-content">
                <div class="blog-meta">
                    <ul>
                        <li>By: <span>Admin</span></li>
                        <li>Sep 14, 2018</li>
                    </ul>
                </div>
                <h4><a href="blog-details.html">Lorem ipsum dolor amet cons adipisicing elit</a></h4>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="blog-wrapper mb-30 gray-bg">
            <div class="blog-img hover-effect">
                <a href="blog-details.html"><img alt="" src="assets/img/blog/blog-7.jpg"></a>
            </div>
            <div class="blog-content">
                <div class="blog-meta">
                    <ul>
                        <li>By: <span>Admin</span></li>
                        <li>Sep 14, 2018</li>
                    </ul>
                </div>
                <h4><a href="blog-details.html">Lorem ipsum dolor amet cons adipisicing elit</a></h4>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="blog-wrapper mb-30 gray-bg">
            <div class="blog-img hover-effect">
                <a href="blog-details.html"><img alt="" src="assets/img/blog/blog-8.jpg"></a>
            </div>
            <div class="blog-content">
                <div class="blog-meta">
                    <ul>
                        <li>By: <span>Admin</span></li>
                        <li>Sep 14, 2018</li>
                    </ul>
                </div>
                <h4><a href="blog-details.html">Lorem ipsum dolor amet cons adipisicing elit</a></h4>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="blog-wrapper mb-30 gray-bg">
            <div class="blog-img hover-effect">
                <a href="blog-details.html"><img alt="" src="assets/img/blog/blog-9.jpg"></a>
            </div>
            <div class="blog-content">
                <div class="blog-meta">
                    <ul>
                        <li>By: <span>Admin</span></li>
                        <li>Sep 14, 2018</li>
                    </ul>
                </div>
                <h4><a href="blog-details.html">Lorem ipsum dolor amet cons adipisicing elit</a></h4>
            </div>
        </div>
    </div>
</div>
<div class="pagination-style text-center mt-20">
    <ul>
        <li>
            <a href="#"><i class="icon-arrow-left"></i></a>
        </li>
        <li>
            <a href="#">1</a>
        </li>
        <li>
            <a href="#">2</a>
        </li>
        <li>
            <a class="active" href="#"><i class="icon-arrow-right"></i></a>
        </li>
    </ul>
</div>
</div>
</div>
{% endblock %}