blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('details/<int:post_id>/', views.blog_details, name='blog_details'),
    path('details/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('category/<slug:category_slug>/', views.blog_by_category, name='blog_by_category'),
    path('tag/<slug:tag_slug>/', views.blog_by_tag, name='blog_by_tag'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('update/', views.cart_update, name='cart_update'),
    path('remove-ajax/', views.cart_remove_ajax, name='cart_remove_ajax'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import logout_view, update_account, update_address, quick_view

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('login-register/', views.login_register, name='login_register'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('my-account/', views.my_account, name='my_account'),
    path('update-account/', update_account, name='update_account'),
    path('update-address/', update_address, name='update_address'),
    path('shop-page/', views.shop_page, name='shop_page'),
    path('shop-page/<str:category_type>/<slug:category_slug>/', views.shop_page, name='shop_page_by_category'),
    path('shop-list/', views.shop_list, name='shop_list'),
    path('shop-list/<str:category_type>/<slug:category_slug>/', views.shop_list, name='shop_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_details, name='product_detail'),
    path('food-category/<slug:category_slug>/', views.product_list_by_food_category,
         name='product_list_by_food_category'),
    path('pet-category/<slug:category_slug>/', views.product_list_by_pet_category, name='product_list_by_pet_category'),
    path('brand/<slug:brand_slug>/', views.product_list_by_brand, name='product_list_by_brand'),
    path('search/', views.search_products, name='search_products'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('quick-view/<int:product_id>/', quick_view, name='quick_view'),
    path('subscribe/', views.subscribe_newsletter, name='subscribe_newsletter'),
]

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_detail, name='wishlist_detail'),
    path('add/<int:product_id>/', views.wishlist_add, name='wishlist_add'),
    path('remove/<int:item_id>/', views.wishlist_remove, name='wishlist_remove'),
]

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Review, ContactMessage


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('An account with this email already exists.')
        return email


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['telephone', 'fax', 'avatar']


class AddressUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'city', 'zip_code', 'country']


class ReviewForm(forms.ModelForm):
    rating = forms.IntegerField(
        required=True,
        error_messages={
            'required': 'Please provide a rating for the product.'
        },
        widget=forms.RadioSelect()
    )

    class Meta:
        model = Review
        fields = ['first_name', 'last_name', 'email', 'rating', 'review_text']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'review_text': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Message'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user and user.is_authenticated:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name
            self.fields['email'].initial = user.email
            self.fields['first_name'].required = False
            self.fields['last_name'].required = False
            self.fields['email'].required = False
            self.fields['first_name'].widget.attrs['readonly'] = True
            self.fields['last_name'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True
        else:
            self.fields['first_name'].required = True
            self.fields['last_name'].required = True
            self.fields['email'].required = True

    def clean_rating(self):
        rating = self.cleaned_data.get('rating')
        if not rating:
            raise forms.ValidationError('Please provide a rating for the product.')
        return rating


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['first_name', 'last_name', 'email', 'subject', 'message']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email Address'}),
            'subject': forms.TextInput(attrs={'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'placeholder': 'Message'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ContactForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name
            self.fields['email'].initial = user.email
            self.fields['first_name'].widget.attrs['readonly'] = True
            self.fields['last_name'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields['first_name'].required = False
            self.fields['last_name'].required = False
            self.fields['email'].required = False

shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.http import url_has_allowed_host_and_scheme
from .models import Product, FoodCategory, PetCategory, Brand, Profile, NewsletterSubscription, DealOfTheWeek
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm, AddressUpdateForm, ReviewForm, ContactForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .utils import ensure_profile_exists
from django.http import JsonResponse
from django.utils.text import Truncator
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.db.models import Avg
from blog.models import Post
from django.utils import timezone


def index(request):
    latest_products = Product.objects.filter(available=True).order_by('-created')[:8]
    latest_posts = Post.objects.order_by('-published_date')[:3]

    deal_of_the_week = DealOfTheWeek.objects.filter(end_date__gte=timezone.now()).first()

    context = {
        'latest_products': latest_products,
        'latest_posts': latest_posts,
        'deal_of_the_week': deal_of_the_week,
    }

    return render(request, 'shop/index.html', context)


def about_us(request):
    return render(request, 'shop/about-us.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST, user=request.user)
        if form.is_valid():
            contact_message = form.save(commit=False)
            if request.user.is_authenticated:
                contact_message.first_name = request.user.first_name
                contact_message.last_name = request.user.last_name
                contact_message.email = request.user.email
            contact_message.save()
            messages.success(request, 'Your message has been sent successfully.')
            return redirect('shop:contact')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ContactForm(user=request.user)

    return render(request, 'shop/contact.html', {'form': form})


def login_register(request):
    return render(request, 'shop/login-register.html')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            messages.success(request, 'Registration successful. Please log in.')
            return redirect('shop:login_register')
        else:
            register_errors = form.errors.get_json_data()
            formatted_errors = []
            for field, errors in register_errors.items():
                for error in errors:
                    formatted_errors.append(f"{field}: {error['message']}")
            return render(request, 'shop/login-register.html', {'register_errors': formatted_errors})
    return redirect('shop:login_register')


def login(request):
    next_url = request.GET.get('next', 'shop:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                if url_has_allowed_host_and_scheme(next_url, allowed_hosts={request.get_host()}):
                    return HttpResponseRedirect(next_url)
                else:
                    return redirect('shop:index')
            else:
                login_errors = 'Incorrect username or password.'
                return render(request, 'shop/login-register.html', {'form': form, 'login_errors': login_errors, 'next': next_url})
        else:
            login_errors = 'Incorrect username or password.'
            return render(request, 'shop/login-register.html', {'form': form, 'login_errors': login_errors, 'next': next_url})
    else:
        form = AuthenticationForm()
        return render(request, 'shop/login-register.html', {'form': form, 'next': next_url})


@login_required
def my_account(request):
    ensure_profile_exists(request.user)

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        address_form = AddressUpdateForm(request.POST, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid() and address_form.is_valid():
            user_form.save()
            profile_form.save()
            address_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('shop:my_account')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        address_form = AddressUpdateForm(instance=request.user.profile)

    countries = ["United States", "Ukraine", "United Kingdom"]
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'address_form': address_form,
        'countries': countries
    }

    return render(request, 'shop/my-account.html', context)


@login_required
def update_account(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            if 'remove_avatar' in request.POST:
                request.user.profile.avatar.delete()
                request.user.profile.avatar = None
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your account information has been updated!')
            return redirect('shop:my_account')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'shop/update-account.html', context)


@login_required
def update_address(request):
    if request.method == 'POST':
        address_form = AddressUpdateForm(request.POST, instance=request.user.profile)
        if address_form.is_valid():
            address_form.save()
            messages.success(request, 'Your address has been updated!')
            return redirect('shop:my_account')
    else:
        address_form = AddressUpdateForm(instance=request.user.profile)

    countries = ["United States", "Ukraine", "United Kingdom"]
    context = {
        'address_form': address_form,
        'countries': countries,
    }

    return render(request, 'shop/update-address.html', context)


@login_required
def logout_view(request):
    next_url = request.GET.get('next', 'shop:index')
    if url_has_allowed_host_and_scheme(next_url, allowed_hosts={request.get_host()}):
        logout(request)
        return HttpResponseRedirect(next_url)
    else:
        logout(request)
        return redirect('shop:index')


def product_details(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    reviews = product.reviews.all()
    review_count = reviews.count()
    overall_rating = reviews.aggregate(Avg('rating'))['rating__avg']

    if request.method == 'POST':
        form = ReviewForm(request.POST, user=request.user)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            if request.user.is_authenticated:
                review.user = request.user
                review.first_name = request.user.first_name
                review.last_name = request.user.last_name
                review.email = request.user.email
            review.save()
            messages.success(request, 'Thank you for your review!')
            return redirect('shop:product_detail', id=product.id, slug=product.slug)
        else:
            for field in form.errors:
                for error in form.errors[field]:
                    messages.error(request, error)
    else:
        form = ReviewForm(user=request.user)

    return render(request, 'shop/product-details.html', {
        'product': product,
        'form': form,
        'reviews': reviews,
        'overall_rating': overall_rating,
        'review_count': review_count,
    })


def shop_list(request, category_slug=None, category_type=None):
    food_categories = FoodCategory.objects.all()
    pet_categories = PetCategory.objects.all()
    brands = Brand.objects.all()
    products = Product.objects.filter(available=True)
    current_category = None

    if category_slug and category_type:
        if category_type == 'food':
            current_category = get_object_or_404(FoodCategory, slug=category_slug)
            products = products.filter(food_category=current_category)
        elif category_type == 'pet':
            current_category = get_object_or_404(PetCategory, slug=category_slug)
            products = products.filter(pet_category=current_category)
        elif category_type == 'brand':
            current_category = get_object_or_404(Brand, slug=category_slug)
            products = products.filter(brand=current_category)

    num_products_per_page = int(request.GET.get('num_products_per_page', 6))

    min_price = request.GET.get('min_price')

templates/shop/shop-list.html
{% extends "shop/base.html" %}
{% load static %}
{% load shop_pagination_tags %}
{% block content %}
<div class="breadcrumb-area pt-95 pb-95 bg-img" style="background-image:url('{% static 'shop/img/banners/banner-2.jpg' %}');">
<div class="container">
<div class="breadcrumb-content text-center">
<h2>Shop Page</h2>
<ul>
    <li><a href="{% url 'shop:index' %}">home</a></li>
    <li class="active">Shop Page</li>
</ul>
</div>
</div>
</div>
<div class="shop-area pt-100 pb-100 gray-bg">
<div class="container">
<div class="row flex-row-reverse">
<div class="col-lg-9">
    <div class="shop-topbar-wrapper">
        <div class="product-sorting-wrapper">
            <div class="product-show shorting-style">
                <label>Showing <span>{{ page_obj.start_index }}-{{ page_obj.end_index }}</span> of <span>{{ paginator.count }}</span> Results</label>
                <form method="get" id="num_products_form">
                    <select name="num_products_per_page" onchange="document.getElementById('num_products_form').submit();">
                        <option value="6" {% if num_products_per_page == 6 %}selected{% endif %}>6</option>
                        <option value="9" {% if num_products_per_page == 9 %}selected{% endif %}>9</option>
                        <option value="12" {% if num_products_per_page == 12 %}selected{% endif %}>12</option>
                    </select>
                    {% if current_category and category_type %}
                        <input type="hidden" name="category_type" value="{{ category_type }}">
                        <input type="hidden" name="category_slug" value="{{ current_category.slug }}">
                    {% endif %}
                </form>
            </div>
        </div>
        <div class="grid-list-options">
            <ul class="view-mode">
                {% if current_category %}
                <li><a href="{% url 'shop:shop_page_by_category' category_type current_category.slug %}?num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}"><i class="ti-layout-grid4-alt"></i></a></li>
                <li class="active"><a href="{% url 'shop:shop_list_by_category' category_type current_category.slug %}?num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}"><i class="ti-align-justify"></i></a></li>
                {% else %}
                <li><a href="{% url 'shop:shop_page' %}?num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}"><i class="ti-layout-grid4-alt"></i></a></li>
                <li class="active"><a href="{% url 'shop:shop_list' %}?num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}"><i class="ti-align-justify"></i></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="grid-list-product-wrapper">
        <div class="product-view product-list">
            <div class="row">
                {% for product in products %}
                <div class="product-width col-lg-6 col-xl-4 col-md-6 col-sm-6">
                    <div class="product-wrapper mb-10">
                        <div class="product-img">
                            <a href="{% url 'shop:product_detail' product.id product.slug %}">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                            <div class="product-action">
                                <a title="Quick View" data-toggle="modal" data-target="#exampleModal" href="#" data-product-id="{{ product.id }}">
                                    <i class="ti-plus"></i>
                                </a>
                                <a title="Add To Cart" href="{% url 'cart:cart_add' product.id %}">
                                    <i class="ti-shopping-cart"></i>
                                </a>
                            </div>
                            <div class="product-action-wishlist">
                                {% if user.is_authenticated %}
                                <a title="Wishlist" href="{% url 'wishlist:wishlist_add' product.id %}">
                                    <i class="ti-heart"></i>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="product-content">
                            <h4><a href="{% url 'shop:product_detail' product.id product.slug %}">{{ product.name }}</a></h4>
                            <div class="product-price">
                                <span class="new">${{ product.new_price }}&nbsp;&nbsp;</span>
                                {% if product.old_price %}
                                <span class="old">${{ product.old_price }}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="product-list-content">
                            <h4><a href="{% url 'shop:product_detail' product.id product.slug %}">{{ product.name }}</a></h4>
                            <div class="product-price">
                                <span class="new">${{ product.new_price }}&nbsp;&nbsp;</span>
                                {% if product.old_price %}
                                <span class="old">${{ product.old_price }}</span>
                                {% endif %}
                            </div>
                            <p>{{ product.description|linebreaksbr|truncatewords:20 }}</p>
                            <div class="product-list-action">
                                <div class="product-list-action-left">
                                    <a class="addtocart-btn" title="Add to cart" href="{% url 'cart:cart_add' product.id %}">
                                        <i class="ion-bag"></i> Add to cart
                                    </a>
                                </div>
                                <div class="product-list-action-right">
                                    {% if user.is_authenticated %}
                                    <a title="Wishlist" href="{% url 'wishlist:wishlist_add' product.id %}">
                                        <i class="ti-heart"></i>
                                    </a>
                                    {% endif %}
                                    <a title="Quick View" data-toggle="modal" data-target="#exampleModal" href="#" data-product-id="{{ product.id }}"><i class="ti-plus"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="pagination-style text-center mt-10">
                <ul>
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}&num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}"><i class="icon-arrow-left"></i></a>
                    </li>
                    {% endif %}

                    {% get_pagination_range page_obj as pagination_range %}
                    {% for page_num in pagination_range %}
                        {% if page_num == '...' %}
                            <li><span>...</span></li>
                        {% else %}
                            <li {% if page_num == page_obj.number %}class="active"{% endif %}>
                                <a href="?page={{ page_num }}&num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}&num_products_per_page={{ num_products_per_page }}{% if request.GET.min_price %}&min_price={{ request.GET.min_price }}{% endif %}{% if request.GET.max_price %}&max_price={{ request.GET.max_price }}{% endif %}"><i class="icon-arrow-right"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="shop-sidebar">
        <div class="shop-widget">
            <h4 class="shop-sidebar-title">Search Products</h4>
            <div class="shop-search mt-25 mb-50">
                <form method="get" action="{% url 'shop:search_products' %}">
                    <input type="text" name="q" placeholder="Find a product" value="{{ request.GET.q }}">
                    <input type="hidden" name="view_type" value="list">
                    <button type="submit">
                        <i class="icon-magnifier"></i>
                    </button>
                </form>
            </div>
        </div>
        <div class="shop-widget">
            <h4 class="shop-sidebar-title">Filter By Price</h4>
            <div class="price_filter mt-25">
                <form method="get" action="{% if current_category %}{% url 'shop:shop_list_by_category' category_type current_category.slug %}{% else %}{% url 'shop:shop_list' %}{% endif %}">
                    <div id="slider-range"></div>
                    <div class="price_slider_amount">
                        <div class="label-input">
                            <label>price : </label>
                            <input type="text" id="amount" name="price" placeholder="Add Your Price" />
                            <input type="hidden" id="min_price" name="min_price" value="{{ request.GET.min_price }}">
                            <input type="hidden" id="max_price" name="max_price" value="{{ request.GET.max_price }}">
                            {% if current_category and category_type %}
                                <input type="hidden" name="category_type" value="{{ category_type }}">
                                <input type="hidden" name="category_slug" value="{{ current_category.slug }}">
                            {% endif %}
                        </div>
                        <button type="submit">Filter</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="shop-widget mt-50">
            <h4 class="shop-sidebar-title">Food Category</h4>
            <div class="shop-list-style mt-20">
                <ul>
                    {% for food_category in food_categories %}
                    <li><a href="{% url 'shop:shop_list_by_category' 'food' food_category.slug %}">{{ food_category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="shop-widget mt-50">
            <h4 class="shop-sidebar-title">Pet Category</h4>
            <div class="shop-list-style mt-20">
                <ul>
                    {% for pet_category in pet_categories %}
                    <li><a href="{% url 'shop:shop_list_by_category' 'pet' pet_category.slug %}">{{ pet_category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="shop-widget mt-50">
            <h4 class="shop-sidebar-title">Top Brands</h4>
            <div class="shop-list-style mt-20">
                <ul>
                    {% for brand in brands %}
                    <li><a href="{% url 'shop:shop_list_by_category' 'brand' brand.slug %}">{{ brand.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% endblock %}